version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tripbook_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tripbook
      MYSQL_USER: tripbook
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'

  mongodb:
    image: mongo:4.4
    container_name: mongodb_tripbook_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
